version: '3.9'

services:
  app:
    build: .
    container_name: app
    command: "bash run_server.sh"
    env_file:
      .envs
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - pgbouncer
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 583eec1d6253e69a3978cbf0ce35bc982
      POSTGRES_DB: kenar_divar
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth=md5
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 583eec1d6253e69a3978cbf0ce35bc982
      ADMIN_USERS: postgres,admin
    restart: always
    ports:
      - "5432:5432"
  redis:
    image: bitnami/redis:latest
    container_name: redis
    environment:
      REDIS_PASSWORD: ReDiseRYsEKRetP@ssV0rD
    restart: always
    ports:
      - "6379:6379"
volumes:
  pgdata: 