# Generated by Django 5.0.1 on 2024-01-31 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divar_homepage', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_token', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=255)),
                ('rate', models.IntegerField(default=0)),
                ('demand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand', to='divar_homepage.divarprofile')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='divar_homepage.divarprofile')),
            ],
        ),
    ]
